Solution 03. 01 Button
js-tasks-ru/htmlcss-20240216_t-klymets pull request #3
Opened 2024-02-27 22:15 UTC by ta-ni

2024-02-27 22:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-28 13:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-04 14:12 UTC, GSemikozov requested changes

2024-03-04 14:12 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.section {
строки 1-7 удалим, общее правильно - в файле стилей компонента стили только этого компонента, врапперы или вспомогательные стили можно оформлять в отдельном файле, а глобальные стили - в таких файлах как main.css / normalize

2024-03-04 14:12 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 182px;
фиксировать ширину не нужно

2024-03-04 14:12 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-width: 1px;
лучше не разбрасывать и оформить все в общем `border`

2024-03-04 14:12 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 182px;
а вот чего не хватает - паддингов

2024-03-04 14:12 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button[disabled],
достаточно .button:disabled

2024-03-06 20:34 UTC, ta-ni commented on 03-lection1/01-button/button.css
> +.section {
Поняла, удалила.

2024-03-06 20:44 UTC, ta-ni commented on 03-lection1/01-button/button.css
> +    width: 182px;
добавила.

2024-03-12 09:44 UTC, GSemikozov requested changes

2024-03-12 09:44 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 50px;
при таких паддингах высота будет 49 а не 48. Советую зафиксировать высоту кнопки height: 48px

2024-03-12 09:53 UTC, ta-ni commented on 03-lection1/01-button/button.css
> +    padding: 15px 50px;
ага, поняла, спасибо.

2024-03-12 14:12 UTC, GSemikozov approved these changes

2024-03-12 14:13 UTC, merged